tap "homebrew/cask-fonts"

brew "dtach"
brew "fish"
brew "git"
brew "htop"
brew "mas"
brew "mercurial"
brew "starship"
brew "the_silver_searcher"
brew "tig"
brew "tldr"
brew "trash"
brew "tree"

cask "1password"
cask "aerial"
cask "alfred"
cask "authy"
cask "bartender"
cask "brave-browser"
cask "caffeine"
cask "choosy"
cask "dash"
cask "doxie"
cask "dropbox"
cask "emacs"
cask "firefox"
cask "fluid"
cask "keybase"
cask "nordvpn"
cask "notion"
cask "postman"
cask "sizeup"
cask "skype"
cask "spotify"
cask "twitch"

cask "font-droid-sans-mono-nerd-font"
cask "font-fira-code-nerd-font"
cask "font-meslo-lg-nerd-font"

mas "Xcode",          id: 497799835
mas "Slack",          id: 803453959
mas "Sip",            id: 507257563
mas "Kiwi for Gmail", id: 986304488
